### ISSUE TITLE
Go SDK WalletService when using multiple wallets

### ISSUE THREAD

**Issue by romanlevin** [Dentity-Development/dentity-ecosystems-sdk#179]
A question about the intended use pattern of `WalletService` in the Go SDK. In a multi-wallet environment, a single `WalletService`  is not thread-safe because in the below case

```
thread1:
  service.SetProfile(profileA)
  service.IssueCredential(documentA)
thread2:
  service.SetProfile(profileB)
  service.IssueCredential(documentB)
```
we can’t guarantee that each document is signed by the intended wallet.

In general this is an unusual pattern in Go, but assuming that’s necessary, the obvious solution is to create a `WalletService` for each wallet we’re working with.

However, from what I can see, each call to `CreateWalletService` creates a new gRPC connection, unless an existing `*grpc.ClientConn` is passed in. Creating a connection for each wallet object is not a great idea because it’s going to be very easy to reach a connection limit somewhere.

Is the intended use-pattern here to create a single `*grpc.ClientConn` and pass it to every call of `CreateWalletService` ?

Is there a reason why `WalletService` doesn’t take a `WalletProfile` for each API call? That would avoid the issue.

Also, under the hood, `CreateChannelIfNeeded` uses `context.Background()` (by calling `grpc.Dial` instead of accepting a context from the user and using `grpc.DialContext` which I’m not sure is a good idea in a library.

**Comment by fundthmcalculus** [comment]
@romanlevin the `CreateChannelIfNeeded` was part of my initial prototype, that can be altered. thread-safety is a good point, the intent would be for you to provide the connection if it should be shared. `WalletService` doesn't take `WalletProfile` because that adds even more arguments to every call. Also, the `TrustRegistryService` requires the `WalletProfile` metadata.

**Comment by romanlevin** [comment]
> thread-safety is a good point, the intent would be for you to provide the connection if it should be shared.

@fundthmcalculus So you're saying the way to use the client with multiple wallets currently is to create a `WalletService` per wallet and reuse the the same `*grpc.ClientConn` between them?

**Comment by fundthmcalculus** [comment]
> > thread-safety is a good point, the intent would be for you to provide the connection if it should be shared.
> 
> @fundthmcalculus So you're saying the way to use the client with multiple wallets currently is to create a `WalletService` per wallet and reuse the the same `*grpc.ClientConn` between them?

That, or I could add the ability to access the channel inside the service, so you can open an additional `WalletService` with an existing one's channel. I generally think that we should handle the system connections, since that's SDK domain. You'd just have to remember that if you dispose of one, you have to dispose of them all. Thinking on that, I dislike that idea since it couples the `WalletService`s to each other?

**Comment by romanlevin** [comment]
Hey @fundthmcalculus I see you've added a `ctx` argument in most places and that's great!

However, `CreateWalletService` still needs this argument because under the hood it calls
https://github.com/trinsic-id/sdk/blob/d7429092e6a9c01352b9136c4947f882cb9a3249/go/services/services.go#L173

instead of `grpc.DialContext`, so if this call hangs for some reason, `CreateWalletService` could block forever.

Alternatively `CreateWalletService` could be lazy, and not actually initiate a connection until the wallet service is used.

**Comment by fundthmcalculus** [comment]
Good catch, @romanlevin , there are some changes coming to the service(s) layout that need to be implemented before that, which is why I held off on some of the changes. The `ctx` parameter will stay for sure, but `WalletService` will be split into `AccountService` and `CredentialService`.

**Comment by fundthmcalculus** [comment]
I've thought about this a bit more, and given parity with the other languages, I think what we will do is keep the 1:1 `WalletService` :`AccountProfile` (<- be aware of `WalletProfile` renamed to `AccountProfile`). However, we will add a `CreateWalletService` function that takes an existing channel so that you can reuse the channels. The new SDK/service/profile layout is a lot better than it was.

And yes, I will add support for a user-provided context on channel open. 👍

**Comment by fundthmcalculus** [comment]
https://github.com/trinsic-id/sdk/pull/243

**Comment by fundthmcalculus** [comment]
Merged, ready for use with latest go sdk from `main`.
