### ISSUE TITLE
Implement Ecosystem management support

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#270]
- [x] #304
- [x] #275
- [x] #274
- [x] #273
- [x] #272
- [x] #271
- [x] #276

**Comment by sethjback** [comment]
For provider calls, the server now expects a metadata key named `ecosystem` that has a value of  the ecosystemId being interacted with. This effects all calls that interact with the `Provider` rpc service, with the exception of `CreateEcosystem` and `AcceptInvite`

**Comment by tmarkovski** [comment]
- Is there a need to set `ecosystem` metadata for other services? 
- What is the standardized metadata key (header name)?
- Should this be included as a configuration key, encoded in the profile or used as a service construction parameter?

Let's make some decisions and explore ideas how to solve this before we implement.

**Comment by tmarkovski** [comment]
The `template`/`schema` service will be working with resources that are scoped to ecosystems, so this solution should be applied there as well.

**Comment by sethjback** [comment]
I would think we should just provide the header if the ecosystem id is set in the sdk, then services that need it will have it.  For the first pass of golang I emulated what we were doing with the wallet profile and just let users set it on the provider service on the fly, then it was checked for in the on the backend. 

We will want to make sure it is included in the checksum that gets validated on the server. 

I went with just `ecosystem` for the header name, but we could change that.

**Comment by tmarkovski** [comment]
Thanks, I found the PR. I see they're added along the other parameters in the base service struct. In other languages, these params are passed thru the constructor, but we should probably consider bundling them into an `Options` model, so we can prevent breaking changes.
For example when going from ctor `ProviderService(ServerConfig, AccountProfile)` to `ProviderService(ServerConfig, AccountProfile, ecosystemId)`.
And similarly, using the builder pattern (which we're currently experimenting with in the Swift sdk), this would be added as another non-breaking option `with(:ecosystemId)` during the service construction.

In terms of headers, there's not much significance how we use the metadata. I found [this SO question](https://stackoverflow.com/questions/3561381/custom-http-headers-naming-conventions) which details the recommendations in some RFCs. It is no longer recommended that we prefix custom headers with `x-`.
However, I do like adding some vendor specific prefix, so that we can do custom header processing/routing/filtering on the requests. For example, we can allow or redirect all requests with headers `trinsic-*` to a certain service, etc. Not sure if we'll ever need to do that, it just feels like being able to identify/select all custom vendor headers to be useful.

**Comment by fundthmcalculus** [comment]
- Given some language libraries we support, we should make all header metadata key ids `lower-case`.
- Having an `Options` class is a good idea, since it is more general than the builder pattern, which is not common in a number of languages we support, as well as being extremely verbose.
- +1 to `trinsic-`, since that makes it obvious what header parameters belong to us.

**Comment by tmarkovski** [comment]
Yeah, I think headers aren't case sensitive anyway. We should keep the `authorization` header, as we'd like to standardize oberon scheme for general use, but all other headers can be `trinsic-` prefixed.
