### ISSUE TITLE
Add support for PHP as a language

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#464]
Persuant to a discussion with @BenjaminPritchard , we should consider support for PHP as a supported language. Further (internal) details here: https://www.notion.so/trinsic/Benjamin-Pritchard-7bf092addda64cf18e3abe0447ba3269#362af949f90d4fc2b8b95204eea620b6

* Wordpress plugin demo?
* Frontend developer support?

Tasks:
- [ ] Update github change request PR to add PHP as a language
- [ ] Compile proto schema definition
- [ ] Okapi (FFI) support.

**Comment by tmarkovski** [comment]
There's gRPC support for PHP, so that layer shouldn't be much of an issue. The challenge is how we can bundle and distribute the native libraries for PHP, in a way that they would work as Wordpress plugins on a cross-platform hosted environment.
In order to move this forward, we'd need a POC showcasing if this can work with a rough estimate required to implement this.

**Comment by BenjaminPritchard** [comment]
BTW, I was thinking to make the initial wordpress plugin work for Trinsic API version 1.0. @michaeldboyd hope i am not speaking out of turn here. But actually wordpress Blogs probably DO NOT need 1000s of transactions per second or anything. And i am wondering if it is OK to just have the trinsic V1 API still available along side the V2, so that wordpress PHP context for example could be 1000x simpler. (RIght now the forked WP plugin just has hard-coded JSON fugli-ness")
Hope that is not speaking out of turn. Obviously I don't know the whole vision. But my understanding is that V1 and V2 API's will both be available for long time. LIke IP4 and IP6?? or am i really wrong with my understanding?? @michaeldboyd what do you think about this?

**Comment by tmarkovski** [comment]
I would say our plan to support v1 is not the same as IPv4 vs IPv6. It's more in the realm of 1-2 years.

**Comment by BenjaminPritchard** [comment]
thank you sir. And Mr. Wordpress Plugin should be useful for next two years on Trinsic API v1?? While we drive user adoption, and eventually update Wordpress Plugin to use V2? Is that OK?? Am I understanding correctly?

**Comment by fundthmcalculus** [comment]
@tmarkovski do we want to close this as a "won't do", since it doesn't sound like there's a major demand for it?

**Comment by tmarkovski** [comment]
Yeah, that makes sense
