### ISSUE TITLE
Move samples for Python, Go, Java and Ruby to `sdk-examples`

### ISSUE THREAD

**Issue by tmarkovski** [Dentity-Development/dentity-ecosystems-sdk#529]
The repository `sdk-examples` is intended to contain self-running samples that use production packages and installation workflows that showcase the use of our SDK in a series of scenarios.
Currently, the above languages link back to the SDK which requires sdk development setup with minimal information how to use and install packages and their requirements.

**Comment by fundthmcalculus** [comment]
The location of those samples is intentional. They are used by the integration tests to verify functionality by language. They are also used by the documentation injection code, which cannot inject code across repositories. As a result, we cannot move these samples out of the repository and into `sdk-examples`. That being said, we could move a COPY of these samples to the `sdk-examples` repository for use with package consumption testing. The caveat is this becomes another thing we have to update whenever new `sdk` or `okapi` packages are released.

Something I noticed last week is that the `sdk-examples` are not immediately updated (bug reports for the dotnet samples) can be an issue. By keeping a tighter connection between the examples and the sdk, we reduce the incidence of outdated code/examples. If we want to keep the samples separate, we need to set up github actions to use the `sdk-examples` repository as the production package consumption testing (not necessarily a bad thing). This would provide a degree of manual separation between production code and the development code. The nightly prod testing would catch when the samples go out of date and alert me that an update (to whatever samples) is required.

My suggestion is that we add better documentation on how to run those samples in the `sdk` repository (`README.md` by language sample directory) and move *all* samples into the `sdk` repository. This is how `protobuf` does it with their [`sample` folder](https://github.com/protocolbuffers/protobuf/tree/main/examples).

**Comment by michaeldboyd** [comment]
As a dev, I want to create a hello world in my language. The documentation should be linked to our replit sample which is running from a github repo, probably `sdk-example` #422
