### ISSUE TITLE
Add `TemplateService.List()`

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#626]
Add a function call to list all credential templates

Languages:
- [ ] .NET
- [ ] Go
- [ ] Java
- [ ] Node
- [ ] Python
- [ ] Ruby
- [ ] Swift
- [ ] Web

**Comment by tmarkovski** [comment]
Motivation? Solution statement?

**Comment by geel9** [comment]
Personally, I have some concerns about the coexistence of the `List` and `Search` endpoints.

As far as I can tell, from an API consumer's perspective, the main differences are:

- `List` has a nice default query; `Search` has no default query.
- `List` returns strongly-typed `TemplateData` objects; `Search` returns raw JSON
  - Therefore, `Search` must be used if you're doing something more complicated than `SELECT *`



I appreciate the ability to execute a query against the template registry which returns data that doesn't map onto `TemplateData`, but I worry about the confusion on the consumer side.


"What's the difference between List and Search?" is a topic we're going to have to explicitly cover. I feel like there's a better way.


Some possible solutions:
- Just rename the endpoints to something like `Search` and `SearchRaw`
  - Clearly communicates what these endpoints _share_ and where they _diverge_.
  - No significant backend code change necessary
  - I'm not married to these _specific_ names; just suggestions off the top of my head.
- Add a `raw` (or some other name) field to `SearchCredentialTemplatesRequest` and remove the `List` endpoint.
  - Change `SearchCredentialTemplatesResponse` to include an `items_json` field; it would be `oneof`'d with `templates`.
  - If a consumer wants raw JSON, they just set `raw` to true and access the `items_json` field.
  - Requires backend code change to execute two different paths based on a single parameter
- Leave as-is; no change


Personally, I'm in favor of option 2; it requires more work on our end, but makes the experience much simpler (and brings it more in line with other services, which only have a single `Search` endpoint).

**Comment by fundthmcalculus** [comment]
> Motivation? Solution statement?

It exists in .NET, but I somehow missed you adding it, this is to bring the other languages up to feature parity with .NET. This is the ongoing problem we have, I don't always see a .net change in time to replicate it everywhere else.

**Comment by fundthmcalculus** [comment]
If we want parity across services, we just have the search endpoint with a default query. This is already supported, and has been for a while. I don't think a default `list` call really helps much. I also generally dislike the `raw` suffix. Default search seems like the best of both worlds, balancing maintenance efforts with API clarity.

**Comment by tmarkovski** [comment]
I'm glad you asked. The reason `List` exists in the template service is just experimental. It always returns strongly typed model and I wanted to see if we can use a better search, where we only provide filter expressions.

Here's the current problem with `List`, it's easy to break it. If you pass "SELECT c.field FROM c" it'll return a bunch of empty objects because the projection value `field` doesn't exist. On the other hand it returns strongly typed object, which is nice, because this object is part of the photo model.

This endpoint should still be considered experimental, until we decide on a good approach for it. It is not final or fully designed (for lack of time).

Ideas how we can improve it:

Change the query to accept expressions or strong model instead. For example the query can be changed to only accept filter expression `id = '123' AND name = 'Alice'`. We can then also expose `OFFSET LIMIT` in a nicer paging model, as well as, `ORDER BY` in a sorting model. We can then construct a query on the server. The idea is to give different approach to querying than pure SQL.

I don't recommend implementing this everywhere, as it is just that, experimental. SQL based search is the way to query data using the SDK.

Also, considering this is a quality of life improvement, the priority is somewhat lower.

**Comment by fundthmcalculus** [comment]
That all makes sense. In the future, please mark experimental endpoints as such. It helps with feature parity as well as documentation.
