### ISSUE TITLE
SDK's should send metadata whenever they have it

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#822]
We should send the metadata if the auth token profile exists, even if the endpoint doesn't require it. The server will simply ignore metadata that we don't need. This reduces complexity on the SDK side, as well as allows more auto generated template code.

Languages:
- [x] .NET #829 
- [ ] CLI
- [ ] Go
- [ ] Java
- [ ] Dart
- [ ] Python
- [ ] Ruby
- [ ] Swift
- [ ] Typescript

**Comment by geel9** [comment]
Per a comment by @tmarkovski in #829 , it seems we may want to *not* always send an auth header.

We *do* need to always send metadata, so that we can add additional metadata (IE #845), but we want to control whether or not we send an auth header.

We have two options in my view:

- Always send auth header; force backend to deal with it.
- (My preference) Add an `authenticated: bool` arg to each lang's `BuildMetadata` function.
  - Defaults to `true`
  - Not a huge deal to automate in `protoc-gen-sdk`

**Comment by geel9** [comment]
I've gone ahead with option #2 -- you can see the .NET implementation in #855 

If we decide to go another route this can be easily changed.

**Comment by fundthmcalculus** [comment]
The solution to #845 automatically solves this problem. Closing this as a duplicate.
